project_name = "carrot"

[tasks]
fmt = "swift format -i --recursive Sources/"
install = "strudel build --install"
relaunch = [
  ":install",
  "pkill -f /Applications/Carrot.app || true",
  "open /Applications/Carrot.app",
]
